name: Verificar Proyecto

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Mostrar archivos
        run: dir

      - name: Mostrar package.json
        run: type package.json