name: Instalar Electron

on:
  push:
    branches:
      - main
      - desarrollo

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Crear package-lock.json
        run: npm install

      - name: Instalar Electron
        run: npm install electron --save-dev

      - name: Mostrar versión de Electron
        run: npx electron --version